### ISSUE TITLE
Sphinx docs version

### ISSUE THREAD

**Issue by jared321** [bandframework/Taweret#103]
The PDF version of the sphinx docs list the document as release 0.1.0, which I suspect is taken from the sphinx file `conf.py`.  Do you want the version of the doc to have its own version number or be tied to the version of the Taweret python package?  For the latter, you should be able to setup the package (if not already done so) so that after importing Taweret in `conf.py` you can get the package's version number from the package itself (e.g., `release = Tawaret.__version__`).

**Comment by asemposki** [comment]
I would be fine with it keeping the same number as the current Taweret version. I will fix this before the v0.4 release.

**Comment by asemposki** [comment]
I attempted the fix above, but it failed. Will figure out how to fix that, since I think we have the version set up in the `__init__` of the package.

**Comment by jared321** [comment]
Make sure that you import `Taweret` in `conf.py` as well.

**Comment by asemposki** [comment]
I think it's working now.

**Comment by asemposki** [comment]
OK now it is building with the simpler `Taweret.__version__` call, so this Issue should be complete.

**Comment by asemposki** [comment]
Look good, closing.
