### ISSUE TITLE
JOSS Review -- Incorrect Installation Instructions

### ISSUE THREAD

**Issue by gchure** [bandframework/Taweret#51]
Hi! I'm [reviewing your paper](https://github.com/openjournals/joss-reviews/issues/6175) for JOSS and am working my way through assessing installation. I've run into some problems and comments, which I'm listing below:

1. The [website documentation](https://bandframework.github.io/Taweret/installation.html) has different installation instructions than the [GitHub repository](https://github.com/bandframework/Taweret#cloning). The former directs installation from git via [danOSU/Taweret](https://github.com/danOSU/Taweret.git), which is not the repository tagged for review in JOSS. Your website documentation installation page should be updated to point to the correct repository [bandframework/Taweret](https://github.com/bandframework/Taweret).

2. The installation instructions on the GitHub repository lists the repository address as `TaweretOrg/Taweret`, not `bandframework/Taweret`. I know it properly redirects, but I think it would be prudent to keep naming consistent. 

3. If it is not installable via `pip` (why not?), please remove the line which states `pip install Taweret` on the [website documentation](https://bandframework.github.io/Taweret/installation.html#installation). 

4. What is the reason you have not hosted `Taweret` on a commonly used package manager (e.g. `conda` or `pip`)? I presume you have a good reason for this, but cloning the repository directly and adding it to `PATH` will decrease the number of people who can easily use your software.

**Comment by ominusliticus** [comment]
Thank you for finding these inconsistencies. They have been remedied in the latest pushes to the repository.
We are working to get Taweret hosted on the python package index (PyPI), but the reason was due time constraints. Once the Actions are setup, we will update the documentation accordingly for installation and contribution guidelines.

**Comment by gchure** [comment]
Great, thanks. I totally understand with the time constraint. This remains blocking, however. Once you have CI/CD and `pip install` properly configured, I'll be satisfied with closing this issue and recommending acceptance of the paper.

**Comment by gchure** [comment]
Hi @ominusliticus, thanks for working on getting Taweret on pip! I just gave it a shot and it appears that this installation does not work on my machine (MacOS 14.1.1), with failure at the point of installing `openbtmixing-1.0`. It appears there is a version mismatch between the metadata and the actual available version. Here's the offending line upon install:

```
Requested openbtmixing from https://files.pythonhosted.org/packages/81/44/6f6fd43c57e695af5eba7acfcc6e7ac9e19b30544356985a67391f6acf59/openbtmixing-1.0.tar.gz (from Taweret) has inconsistent version: expected '1.0', but metadata has '1.0.2'
ERROR: Could not find a version that satisfies the requirement openbtmixing (from taweret) (from versions: 1.0)
ERROR: No matching distribution found for openbtmixing
```

Here is the full stacktrace: [openbt_install_failure.txt](https://github.com/bandframework/Taweret/files/14609153/openbt_install_failure.txt)

This appears to be an error not in Taweret, but in openbtmixing as `pip install openbtmixing` yields the same issue. I think it results from [`pyproject.toml`](https://github.com/jcyannotty/OpenBT/blob/main/pyproject.toml) and [`builddist.py`](https://github.com/jcyannotty/OpenBT/blob/main/builddist.py) defining different versions (`1.0.1` vs `1.0`).

**Comment by jcyannotty** [comment]
Hi @gchure, thanks for pointing this out! We did not get this error when testing things ourselves. Everything is updated and pushed to pypi now. Feel free to try the pip install whenever you get a chance.

**Comment by gchure** [comment]
Successfully installed on my end. Congrats!
