### ISSUE TITLE
JOSS Paper review - language comments

### ISSUE THREAD

**Issue by julienmalard** [bandframework/Taweret#55]
Minor language comments:

- Footnote 1: Recommend writing "hippopotamus" in full
- Line 66: Should read "data"
- Line 70: The sentence seems incomplete
- Line 104: sum-to-one should not be hyphenated
- Lines 157-158: did you mean "for individual contributions" or "for contributing individuals"?

**Comment by asemposki** [comment]
Hi Julien, 

Thank you for your careful read of our manuscript! The changes you requested have been made and pushed to the `joss-submission` branch, and should now be reflected in the generated paper draft.

**Comment by julienmalard** [comment]
Hello,

I was unable to find the updated generated paper draft (the latest I can find is from Jan 30th). Feel free to mark this issue as completed if these are indeed corrected in the most recent draft.
