### ISSUE TITLE
Codecov only assessing coverage in `tests.py`

### ISSUE THREAD

**Issue by gchure** [bandframework/Taweret#81]
It looks like your codecov reporting is only showing that pytest is running the scripts in `test.py`, and not reporting the actual code coverage over `Taweret/*/*`. You may have Taweret blocked in your [codecove settings `yml`](https://docs.codecov.com/docs/codecov-yaml).

**Comment by ominusliticus** [comment]
The codecov report has been updated to cover the whole package. So I am closing this issure
